### ISSUE TITLE
Reasons not to use serde?

### ISSUE THREAD

**Issue by chpio** [rust-fcp/rust-simple-bencode#1]
Hi,
what are your reasons not to use serde? Mainly the performance?

**Comment by progval** [comment]
Does Serde support serializing a dict whose values are byte arrays?

**Comment by chpio** [comment]
do we need this in cjdns?
edit: there is also an ["Value"](https://docs.rs/serde_bencode/0.1.3/serde_bencode/bencode_enum/enum.Bencode.html) struct supporting this

**Comment by progval** [comment]
> do we need this in cjdns?

Yes. See https://github.com/cjdelisle/cjdns/blob/cjdns-v19.1/doc/Whitepaper.md#keys-of-a-router-messages-dictionary . In particular, `txid` is an arbitrary byte string

**Comment by progval** [comment]
>  edit: there is also an "Value" struct supporting this

Cool. I am not sure I want to add a dependency as big as Serde, but I will consider it.

**Comment by chpio** [comment]
ohh, you wrote "value"... yeah, that's not a problem. but if you need a byte string as a key you have to use Value or HashMap
